### PR TITLE
Empty fields

### PR DESCRIPTION
**Pull request by skullwritter**
resolves the empty fields not updating,
resolves the total removal of field content and fields not updating
because they are not posted to the $_POST request

### CODE REVIEW

**Comment by elliotcondon** [comment]
Hi @adomasalcore3 

Thanks for the PR.

Can you please elaborate more on why this would be required?

Is this to remove old values that have been saved for the post, but the fields no longer exist?

The code you have posted includes some logic errors, and would cause large performance issues due to the loading of every field of a post.

I won't be merging this in, but am interested in the root of the issue

**Comment by adomasalcore3** [comment]
i work with wordpress everyday, and for example, if i create a field on a post type, and alter it, when i go to delete the hole content the field has, it stay the same, for example, on the text fields you can replace with an space, but on files fields and others that don't have an visible text field, fou have to have at least one thing there or put only final content. (sorry for the bad english, bellow representation of steps)
----------on new post---------------
->create to post type example
->post type example
-> new 
->fill the content
->save
->try to delete the hole content
->stays the same,like the user hasn't delete the content

----------on an saved post---------------
->create to post type example
->post type example
-> edit
->fill the content
->save
->try to delete the hole content
->stays the same,like the user hasn't delete the content

thanks,
Adomasalcore3

**Comment by adomasalcore3** [comment]
on programmatic view, (right now - without the correction)
on save, sends only the filled fields,
don't check the fields that are empty, because they are not in the $_POST request
saves only the $_POST variables
(with correction)
On save, sends only the filled fields,
check if all fields are in the post request
if any isn't, delete the content from the db on the specific field that isn't on the post request

**Comment by adomasalcore3** [comment]
tested the correction, it works like an charm now (before i sent here the correction)

**Comment by adomasalcore3** [comment]
on: "Is this to remove old values that have been saved for the post, but the fields no longer exist?"
it updates the field, to be with empty content (empty string)
it is to update only (update) the empty fields that don't appear on the post request, because PHP do not show them if they are empty on post requests, not to delete them.
Quote from the code:
-> update_field( $id, '', $post_id ); (parse the empty fields to be updated with no content if there are not in the post request)

**Comment by adomasalcore3** [comment]
now.... the performance issues, i only gave one possible issue, of corse, since you know all the code of the plugin, you an come with an best solution than mine for that. (update the fields that where with content and now they need to be empty, because the user wanted to delete the hole content of the field)

**Comment by adomasalcore3** [comment]
(again, sorry for the english, i have to be fast typing to answer you because i'm working)

**Comment by elliotcondon** [comment]
Hi @adomasalcore3 

Thanks for the replies.

We have a few topics in this discussion, but there is 1 major issue I would like to address.

You are suggesting that it is not possible to save a blank value. This is not true. You can always save a blank value, and it will update the DB.

If you are not able to save a blank value (to clear a previously saved value), there is a serious bug that needs to be fixed on your site. Perhaps a custom function is removing blank values from the $_POST?

Have you tested what is in the $_POST array during the save_post action?

**Comment by adomasalcore3** [comment]
yes, the post data does not return all of the fields, the blank disapear from the var ($_POST)
in a var_dump($_POST), it only says some of them, equaly on print_r($_POST)

**Comment by adomasalcore3** [comment]
...the blank fields disapear ....

**Comment by adomasalcore3** [comment]
i've tested in several templates and it is allways the same problem...
i've searched, and it is because of the filtration of the post that happen on the serverside

**Comment by adomasalcore3** [comment]
that's why i've made the pullrequest, because it is many servers with that problem

**Comment by adomasalcore3** [comment]
maybe, on the future, i can make an more reliable block of code.... but now i'm a bit busy....

**Comment by adomasalcore3** [comment]
(i've made the changes on that code in a rush)
`$fields = get_fields();
			$left=array();
			foreach($fields as $field_name=>$value):
				$temp=get_field_object($field_name, $post_id);
				if(!isset($_POST['fields'][$temp['key']]))
				{
					//on post it gives the "$ID" needed...
					update_field( $id, '', $post_id );
				}
			endforeach;`
what you think about preformance now? (if the code is correct, i've not test it but the sintax is probably correct)

**Comment by adomasalcore3** [comment]
Checked.... working

**Comment by elliotcondon** [comment]
Hi @adomasalcore3 

Thanks for the replies.

In the future, can you please write 1 clear comment instead of multiple short vague ones?

The code you have written may work, but it is not needed.
The issue you are experiencing is unique to your website and I can't replicate it.

Please leave your code for now and allow me to help you solve the issue at the root.

This is what I understand of your issue:
- When you save a post, any blank value is not sent in the $_POST data.
- You have performed debugging in the save_post action and can confirm this.
- This issue is preventing you from saving any blank values over existing ones

Please understand this is NOT an issue with the plugin. I can confirm 100%, ACF will allow you to save a blank value.

You mentioned in a previous comment "i've searched, and it is because of the filtration of the post that happen on the serverside". Can you please elaborate more on this 'filtration'?
What is the code that is removing blank values, and there is this code found?

**Comment by adomasalcore3** [comment]
on the server side, apears to have an filtration by the server. them made by the server it self.
the lines of the correction for this servers are:
895 to 907 of patch-1 (you will see it on the printscreen)
captura de tela 42
it will look for all the fields saved on the post, and if any don't exist in the post variable, it will replace it with empty values
the servers from my company (where i work) are making the filtration, also the xampp(i've had activated mod security because it's required on my work) makes it. ($_POST not returning the empty values).
on the request they apear, but on serverside, they don't...
 i wish to be able to give you an phpinfo, but because of my work, i cannot do it.
i can only say that it haves mod security, mod rewrite more (i don't know the rest from head...)

**Comment by elliotcondon** [comment]
Hi @adomasalcore3 

Thanks for the reply.

I understand your code and where to put it, there is no need to remind me of the code in each reply.
I do not wish to add this code to the plugin to fix the issue specific with your server.

With millions of installations, this is the first occurrence of this issue and will cause problems with any input, not only from ACF, but from WP itself.

I think you need to solve this issue at the root of the problem (your server filtration), not in ACF.

**Comment by adomasalcore3** [comment]
ok thanks

**Pull request closed without merging**
