### PR TITLE
Translation pt_PT update

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by elliotcondon** [comment]
Thanks @pedro-mendonca 

i may have merged these 2 PR's in the incorrect order.

Can you please pull the latest files and check the difference between this github repo's pt_PT files and your own?

**Comment by pedro-mendonca** [comment]
I'm not sure the order would make any difference, still, You did accept both my PR to this repo in the correct order, everything is ok, my `master`and `localization-pt_PT`branches are synced with your `master`.

https://github.com/elliotcondon/acf/compare/master...pedro-mendonca:localization-pt_PT

**Comment by pedro-mendonca** [comment]
screenshot 2016-04-28 08 22 16

**Comment by elliotcondon** [comment]
Awesome! Always good to double check

**Pull request merged**
