### PR TITLE
Interact with the post after setting the terms.

### PR DESCRIPTION
**Pull request by styledev**
This do_action allows the developer to use the newly set terms that are saved for the post.

### CODE REVIEW

**Comment by elliotcondon** [comment]
Hi @styledev 

Thanks for the topic.

I like the idea of this action, but may be better to also include the $post_id, $term_ids and $taxonomy.
Perhaps the action should be renamed 'acf/fields/taxonomy/set_terms' to better match existing naming.

How does this sounds to you?

**Comment by elliotcondon** [comment]
Hi @styledev 

Could you please provide some context for the need of this action?
How would you use this in your project?

**Comment by styledev** [comment]
@elliotcondon – I am using it for duplicating or syncing changes made to a post that utilizes an ACF form. The issue I was having was that I could not find a good way to hook in after the terms had been updated, only before.

As for the extra params and naming convention that sounds good to me! Thanks

**Comment by elliotcondon** [comment]
Hi @styledev 

DId you try using the acf/update_value filter or acf/save_post action?
If so, what didn't work?

**Comment by styledev** [comment]
Honestly, I did this about 6 months ago and forgot to write up the PR then. I just spent some time reviewing the action and filter you noted above, I remember trying to get what I needed to work with them before but I couldn't remember why they didn't work.

After testing it out the update filter still did not give me access to all the taxonomy values I needed in one fell swoop, I would have to target each taxonomy relationship and update everything piece meal. 

As for the action the post at this point doesn't seem to have the updated taxonomy terms yet. 

A little more insight, I have one form where you can submit an action. In that action you can assign it to multiple people. I then trigger my code on acf/set_terms and duplicate the action post for each person as I need individual posts per action per person.

**Comment by elliotcondon** [comment]
Hi @styledev 

Thanks for the reply.

The taxonomy terms will be saved to the post during the 'acf/save_post' action with priority 15.

if you hook into the 'acf/save_post' at priority 20, the terms will be saved and your duplicate code should work as expected.

**Comment by styledev** [comment]
@elliotcondon – wp_get_post_terms/wp_get_object_terms returns an empty array when using acf/save_post with priority 20 or higher.

**Comment by elliotcondon** [comment]
Hi @styledev 

Thanks for the reply.

I just did some testing and found/fixed the issue.
Can you please pull the latest files and try the issue again?

**Comment by elliotcondon** [comment]
* Terms will now be available during the acf/save_post action as expected

**Comment by styledev** [comment]
@elliotcondon – I am using ACF Pro for the site in question, when I swap it out for the master version here I lose my custom fields... also not seeing any updates to master here or latest tag...

**Comment by elliotcondon** [comment]
Hi @styledev 

Thanks for the reply.

Sorry, I thought this issue was posted on the ACF PRO ticket tracker.

All my above responses are for the ACF PRO repo.
I will attach the updated ACF PRO taxonomy field file:
[taxonomy.php.zip](https://github.com/elliotcondon/acf/files/292719/taxonomy.php.zip)

**Comment by styledev** [comment]
@elliotcondon – That worked! Thanks. Where is the ACF Pro Ticket Tracker?

**Comment by elliotcondon** [comment]
Hi @styledev 

I've got a private ACF PRO repo setup with a group of testers.

I also have a support ticket system which I use to provide answers / recieved bug reports:
http://support.advancedcustomfields.com/

**Comment by styledev** [comment]
@elliotcondon – Ah, I thought so, if you need more testers I would be more than happy to help. Thanks for getting this fixed!

**Pull request closed without merging**
