### PR TITLE
Adding bulgarian translation

### PR DESCRIPTION
**Pull request by tyxla**
Added bulgarian (bg_BG) translation.

### CODE REVIEW

**Comment by tyxla** [comment]
Hello,

Is there any reason to delay getting the bulgarian language in the core? More than a year has passed since I submitted the PR.

Thanks,
Marin

**Comment by elliotcondon** [comment]
Hi @tyxla 

Thanks for the prompt. I must have missed this PR, sorry.

I've just merged it in!

**Comment by tyxla** [comment]
Hi @elliotcondon,

Well, that was fast! Thanks for the swift response.

Since the PR is more than a year old, I'll soon check if there are any updates to be done to the translation.

**Comment by elliotcondon** [comment]
awesome!

**Comment by elliotcondon** [comment]
Hi @tyxla 

I haven't got a bulgarian translation for the ACF PRO version yet, would you like to be involved?
I can add you to the ACF PRO github repo and you can then get a hold of ACF PRO.

How does that sound?

**Comment by tyxla** [comment]
@elliotcondon: that sounds awesome! I'd love to get involved.

**Comment by elliotcondon** [comment]
Thanks @tyxla 

I've just added you to the translators group!
Enjoy ACF PRO!

Great work on your portfolio, very nice

**Comment by tyxla** [comment]
Thanks! :)

**Pull request merged**
