### PR TITLE
Welsh language cy_GB

### PR DESCRIPTION
**Pull request by carlmorris**
.po and .mo files for Welsh language cy_GB

### CODE REVIEW

**Comment by elliotcondon** [comment]
Hi @carlmorris 

Thanks for the translation!
Would you be available to translate the ACF PRO version?
I can grant you access to the ACF PRO repo, just let me know.

**Comment by carlmorris** [comment]
Hi @elliotcondon 

I can take a look.

Is the PRO version GPL-licensed? (I couldn't find the answer easily on the web.)

**Comment by elliotcondon** [comment]
Hi @carlmorris 

Why do you ask?

The ACF PRO is a premium version that is not publicly distributed.
It is sold on the ACF website and is held in a private github repo for translators / testers.

**Comment by pedro-mendonca** [comment]
Hi @elliotcondon 
Do you need pt_PT for ACF Pro?

**Comment by elliotcondon** [comment]
Hi @pedro-mendonca 

I have pt_BR, but not pt_PT

**Comment by pedro-mendonca** [comment]
Ok, I just found out the info on this on your site, I've submitted a ticket, I can do it if you need so, as I've been doing for the free version. Feel free to let me know if you need/want it. Thanks.

**Pull request merged**
