### PR TITLE
get correct language of relationship using wpml

### PR DESCRIPTION
**Pull request by mmeester**
In some cases all posts would show `ICL_LANGUAGE_CODE` instead of correct wpml language, with this fix this is solved

### CODE REVIEW

**Comment by elliotcondon** [comment]
Hi @mmeester 

Thanks for the bug report and fix.

Can you please elaborate more on the issue.

Normally, only 1 language of posts can be viewed at one time and this shouldn't be an issue.
Can you describe when multiple languages would be visible?

Thanks
Elliot

**Comment by mmeester** [comment]
Hi @elliotcondon,

Most of the time it should show 1 language of a post but wpml seems to be broken on our end because of the immense number of posts. This at least fixes the issue if the posts are broken.

**Comment by elliotcondon** [comment]
Hi @mmeester 

Thanks for the reply.

I'm not comfortable merging in a fix to a problem that is not clearly described and replicate-able.
I'm happy to chat about the issue and figure out the root of the problem further, so please let me know more about the WPML issue with lots of posts.

**Comment by mmeester** [comment]
I agree, but here's the problem, wpml links all the posts correctly but the selection shows individual posts with the same language (see screenshots)
screen shot 2016-05-10 at 13 20 30
screen shot 2016-05-10 at 13 21 14

**Comment by elliotcondon** [comment]
Hi @mmeester 

Thanks for the screenshot. This does not look correct and I'll do some local testing with this today

**Comment by elliotcondon** [comment]
Hi @mmeester 

I've just done some testing, but can't get multiple translated posts to appear in the relatinoship search results.

If I am editing an english post, only english posts show in the relationship field.
When editing a different language, only that language's posts show.

perhaps you have some code that is allowing multiple language's posts to show?

**Pull request closed without merging**
